Repository recursion-team-v/bomb, pull requests merged in 2023-01, with the labels that each got.

#300 ロビー周りを一通り実装
  backend/src/constants/constants.ts
  backend/src/game_engine/services/playerService.ts
  backend/src/rooms/GameRoom.ts
  backend/src/rooms/schema/GameRoomState.ts
  frontend/public/assets/se/select.mp3
  frontend/public/assets/se/select1.mp3
  frontend/src/PhaserGame.ts
  frontend/src/characters/Player.ts
  frontend/src/config/config.ts
  frontend/src/events/GameEvents.ts
  frontend/src/scenes/GameHeader.ts
  frontend/src/scenes/Lobby.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/scenes/Title.ts
  frontend/src/services/Network.ts
  frontend/src/utils/title.ts
  frontend/src/utils/ui.ts
Labels: size/XL

#308 アイコンの修正
  frontend/public/icon/favicon.ico
Labels: size/XS

#309 OGPの追加
  frontend/index.html
  frontend/vite.config.ts
Labels: size/S

#310 Game -> Lobby の実装
  backend/src/rooms/schema/GameState.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/GameResult.ts
  frontend/src/scenes/Lobby.ts
  frontend/src/services/Network.ts
Labels: size/L

#311 ゲーム開始演出後にタイマーをスタートさせる
  backend/src/constants/constants.ts
  frontend/src/scenes/GameHeader.ts
  frontend/src/utils/drawMap.ts
Labels: size/S

#287 CPU の追加
  backend/package-lock.json
  backend/package.json
  backend/src/constants/constants.ts
  backend/src/game_engine/services/blastService.ts
  backend/src/game_engine/services/bombService.ts
  backend/src/game_engine/services/enemyService.ts
  backend/src/game_engine/services/playerService.ts
  backend/src/rooms/GameEngine.ts
  backend/src/rooms/GameRoom.ts
  backend/src/rooms/schema/Bomb.ts
  backend/src/rooms/schema/Enemy.ts
  backend/src/rooms/schema/GameRoomState.ts
  backend/src/rooms/schema/Player.ts
  backend/src/rooms/schema/Timer.ts
  backend/src/utils/calc.ts
  backend/src/utils/map.ts
  frontend/src/characters/OtherPlayer.ts
  frontend/src/items/Bomb.ts
  frontend/src/scenes/Game.ts
  frontend/src/services/Map.ts
Labels: size/XXL

#315 go to lobby を右側にした
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#312 存在しない keyboard の画像削除 & bomb_point_penetration 画像の追加
  frontend/public/assets/items/bomb/bomb_point_penetration.png
  frontend/src/scenes/Preloader.ts
Labels: size/XS

#313 ブロック数が減ってきた時に敵が止まるバグを修正
  backend/src/game_engine/services/enemyService.ts
Labels: size/S

#325 タイトルでボムのアニメーションも入れた
  frontend/src/utils/usage.ts
Labels: size/XS

#324 アイテムの無敵時間を調整
  backend/src/constants/constants.ts
Labels: size/XS

#322 リザルトに遷移する時のアニメーション追加
  frontend/public/assets/flares.json
  frontend/public/assets/flares.png
  frontend/public/assets/stage_curtain.png
  frontend/public/assets/trophy.png
  frontend/public/assets/winner_cup.png
  frontend/src/anims/CurtainAnims.ts
  frontend/src/anims/TrophyAnims.ts
  frontend/src/config/config.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/GameResult.ts
  frontend/src/scenes/Lobby.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/utils/result.ts
Labels: size/L

#326 フォントを全て同じものを使う
  frontend/src/characters/Player.ts
  frontend/src/scenes/GameHeader.ts
  frontend/src/scenes/GameResult.ts
  frontend/src/utils/ui.ts
Labels: size/S

#327 loading message を追加
  frontend/src/scenes/Preloader.ts
Labels: size/XS

#329 monitor に basic auth 追加
  backend/src/constants/constants.ts
  backend/src/index.ts
  package-lock.json
  package.json
Labels: size/S

#345 add express-basic-auth in backend
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
Labels: size/XS

#334 add README
  README.md
Labels: size/M

#346 デフォルトキャラを cat にした
  backend/src/constants/constants.ts
  frontend/src/utils/usage.ts
Labels: size/XS

#344 アイテムのリソースを手作りに変更
  frontend/public/assets/items/item_heart.png
  frontend/src/scenes/Title.ts
  frontend/src/utils/usage.ts
Labels: size/S

#321 #305,306リザルトの表示バグを修正
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#330 #286 リザルトにBGMを追加
  frontend/public/assets/bgm/result.mp3
  frontend/src/scenes/GameResult.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/scenes/Title.ts
Labels: size/S

#350 リザルトでの敗者のアニメーションを修正
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#348 ゲームタイトルに背景追加
  README.md
  frontend/public/assets/title_background.png
  frontend/src/anims/TitleBackground.ts
  frontend/src/config/config.ts
  frontend/src/scenes/GameResult.ts
  frontend/src/scenes/Lobby.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/scenes/Title.ts
  frontend/src/utils/title.ts
  frontend/src/utils/ui.ts
  frontend/src/utils/usage.ts
Labels: size/M

#347 トロフィーをドット絵にした
  README.md
  frontend/public/assets/trophy.png
Labels: size/XS

#349 ゲームスタートのフォント変更
  README.md
  frontend/public/assets/battle_start_down.png
  frontend/public/assets/battle_start_up.png
  frontend/src/scenes/Game.ts
Labels: size/XS

#351 Update README.md
  README.md
Labels: size/XS

#362 タイトルロゴ入れ替え
  frontend/public/assets/title.png
  frontend/src/scenes/Title.ts
Labels: size/S

#352 花火をドットぽくした
  frontend/public/assets/flares.png
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#353 不要なサウンドを削除し、使ってない keyboard の load を削除
  frontend/public/assets/bgm/stage.mp3
  frontend/public/assets/bgm/stage_1.mp3
  frontend/src/scenes/Game.ts
  frontend/src/scenes/Preloader.ts
Labels: size/S

#354 ボムの照準を足跡にした
  README.md
  frontend/public/assets/items/bomb/bomb_point.png
  frontend/src/items/Bomb.ts
Labels: size/XS

#360 HPを表示する
  frontend/src/characters/Player.ts
  frontend/src/scenes/GameHeader.ts
Labels: size/S

#361 プレイヤーが重なった時に自分が優先になるようにした
  backend/src/constants/constants.ts
  frontend/src/characters/EnemyPlayer.ts
  frontend/src/characters/OtherPlayer.ts
Labels: size/S

#359 リザルトのロゴ変更
  frontend/public/assets/draw_game.png
  frontend/public/assets/winner.png
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#355 効果音のクレジット追加
  README.md
Labels: size/XS

#358 構成図と技術スタック追加
  README.md
  image/architecture.drawio.png
Labels: size/S

#356 Create LICENSE.md
  LICENSE.md
Labels: size/L

#363 カスタムカーソルにした
  README.md
  frontend/public/assets/icons/cursor.png
  frontend/src/scenes/Title.ts
  frontend/src/utils/key.ts
Labels: size/XS

#365 アイコンなどを差し替え
  frontend/public/assets/icons/volume_off.png
  frontend/public/assets/icons/volume_on.png
  frontend/public/assets/keyboard/down.png
  frontend/public/assets/keyboard/left.png
  frontend/public/assets/keyboard/right.png
  frontend/public/assets/keyboard/space.png
  frontend/public/assets/keyboard/space_center.png
  frontend/public/assets/keyboard/space_left.png
  frontend/public/assets/keyboard/space_right.png
  frontend/public/assets/keyboard/top.png
  frontend/public/assets/nameBar.png
  frontend/src/scenes/GameHeader.ts
  frontend/src/scenes/Lobby.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/scenes/Title.ts
  frontend/src/services/SoundVolume.ts
  frontend/src/utils/title.ts
  frontend/src/utils/usage.ts
Labels: size/M

#367 fix lobby error "no room default"
  frontend/src/scenes/Lobby.ts
Labels: size/XS

#364 マップのアセットを差し替える
  backend/src/constants/constants.ts
  backend/src/rooms/schema/Map.ts
  backend/src/rooms/schema/MapTiles.ts
  frontend/public/assets/map/block.png
  frontend/public/assets/map/ground/grass_1.png
  frontend/public/assets/map/ground/grass_2.png
  frontend/public/assets/map/ground/ground_bottom.png
  frontend/public/assets/map/ground/ground_bottom_left.png
  frontend/public/assets/map/ground/ground_bottom_right.png
  frontend/public/assets/map/ground/ground_left.png
  frontend/public/assets/map/ground/ground_right.png
  frontend/public/assets/map/ground/ground_top.png
  frontend/public/assets/map/ground/ground_top_left.png
  frontend/public/assets/map/ground/ground_top_right.png
  frontend/public/assets/map/ground/plants.png
  frontend/public/assets/map/ground/rock_1.png
  frontend/public/assets/map/ground/rock_2.png
  frontend/public/assets/map/tile_walls.png
  frontend/public/assets/tile_grounds.png
  frontend/src/anims/MapAnims.ts
  frontend/src/items/Block.ts
  frontend/src/items/Wall.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/types/GameObjectFactory.d.ts
  frontend/src/utils/drawMap.ts
Labels: size/L

#368 ボムの画像を変更
  frontend/public/assets/items/bomb/bomb.png
  frontend/public/assets/items/bomb/bomb_point.png
  frontend/public/assets/items/bomb/center_blast.png
  frontend/public/assets/items/bomb/center_blast_penetration.png
  frontend/public/assets/items/bomb/horizontal_blast.png
  frontend/public/assets/items/bomb/horizontal_blast_penetration.png
  frontend/public/assets/items/bomb/horizontal_end_blast.png
  frontend/public/assets/items/bomb/horizontal_end_blast_penetration.png
Labels: size/XS

#371 feat/adjust bmg volume riddle
  backend/src/constants/constants.ts
  frontend/public/assets/bgm/battle_start.mp3
  frontend/public/assets/bgm/drow.mp3
  frontend/public/assets/bgm/lose.mp3
  frontend/public/assets/bgm/result.mp3
  frontend/public/assets/bgm/stage.mp3
  frontend/public/assets/bgm/win.mp3
  frontend/public/assets/se/bomb.mp3
  frontend/public/assets/se/game_over.mp3
  frontend/public/assets/se/get_item.mp3
  frontend/public/assets/se/hit_player.mp3
  frontend/public/assets/se/select.mp3
  frontend/public/assets/se/select1.mp3
  frontend/src/characters/MyPlayer.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/Preloader.ts
Labels: size/M

#374 マルチタップを有効化
  frontend/src/utils/key.ts
Labels: size/XS

#377 volume icon の位置を調整
  frontend/src/scenes/GameHeader.ts
Labels: size/S

#372 lobby のアイコンを差し替え
  frontend/public/assets/board.png
  frontend/public/assets/check.png
  frontend/public/assets/child_board.png
  frontend/public/assets/cross.png
  frontend/public/assets/slider_thumb.png
  frontend/src/scenes/Preloader.ts
  frontend/src/utils/ui.ts
Labels: size/M

#373 タイトルとリザルトを調整
  frontend/src/scenes/GameResult.ts
  frontend/src/utils/title.ts
  frontend/src/utils/usage.ts
Labels: size/M

#378 デバッグモード追加
  backend/src/constants/constants.ts
  backend/src/game_engine/services/enemyService.ts
  backend/src/index.ts
  backend/src/rooms/GameRoom.ts
  backend/src/rooms/schema/Enemy.ts
  backend/src/rooms/schema/Player.ts
  frontend/src/PhaserGame.ts
  frontend/src/config/config.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/GameHeader.ts
  frontend/src/scenes/GameResult.ts
  frontend/src/scenes/Title.ts
  frontend/src/services/Network.ts
  frontend/src/utils/debug_menu.ts
  frontend/src/utils/drawMap.ts
  frontend/src/utils/key.ts
Labels: size/L

#385 リザルトにもボリュームアイコン追加
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#382 ゲームの時間を2分にした
  backend/src/constants/constants.ts
Labels: size/XS

#387 tailwindcss,recoil,react-router-domをpackage.jsonから削除
  frontend/package-lock.json
  frontend/package.json
  frontend/src/RouterConfig.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/tailwind.config.cjs
Labels: size/M
