Repository recursion-team-v/bomb, pull requests merged in 2023-02, with the labels that each got.

#388 勝者の名前の位置を微調整
  frontend/src/scenes/GameResult.ts
Labels: size/XS

#384 スタート時にCPUの動き出しが早いのでdelay追加
  backend/src/rooms/schema/Timer.ts
Labels: size/XS

#391 落ちてくるブロックに暫定のアセットを設定
  frontend/src/items/Wall.ts
Labels: size/XS

#381 雲を追加
  README.md
  backend/src/constants/constants.ts
  frontend/public/assets/cloud.png
  frontend/src/config/config.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/services/Cloud.ts
Labels: size/M

#394 inner wall を石に戻した
  frontend/src/items/Wall.ts
Labels: size/XS

#393 雲の透明度と頻度を変更
  frontend/src/config/config.ts
  frontend/src/services/Cloud.ts
Labels: size/XS

#390 アイテムのリソースのデザイン変更
  frontend/index.html
  frontend/public/assets/items/item_bomb_strength.png
  frontend/public/assets/items/item_bomb_up.png
  frontend/public/assets/items/item_heart.png
  frontend/public/assets/items/item_player_speed.png
  frontend/public/favicon/favicon.ico
  frontend/public/icon/favicon.ico
Labels: size/XS

#392 マップの幅・高さをクライアントから設定できるようにした
  backend/src/constants/constants.ts
  backend/src/game_engine/services/dropWallService.ts
  backend/src/game_engine/services/enemyService.ts
  backend/src/game_engine/services/mapService.ts
  backend/src/game_engine/services/playerService.ts
  backend/src/rooms/GameEngine.ts
  backend/src/rooms/GameRoom.ts
  backend/src/rooms/schema/GameMap.ts
  backend/src/rooms/schema/GameRoomState.ts
  backend/src/rooms/schema/Player.ts
  backend/src/types/gameRoom.d.ts
  backend/src/utils/calc.ts
  backend/src/utils/getInitialPlayerPos.ts
  backend/src/utils/map.ts
  frontend/src/PhaserGame.ts
  frontend/src/events/GameEvents.ts
  frontend/src/scenes/Game.ts
  frontend/src/scenes/GameHeader.ts
  frontend/src/scenes/GameResult.ts
  frontend/src/scenes/Lobby.ts
  frontend/src/scenes/Preloader.ts
  frontend/src/scenes/Title.ts
  frontend/src/services/Map.ts
  frontend/src/services/Network.ts
  frontend/src/utils/calcGameScreen.ts
  frontend/src/utils/debug_menu.ts
  frontend/src/utils/drawMap.ts
  frontend/src/utils/ui.ts
Labels: size/XL

#397 Github Repo のリンクを追加
  README.md
  frontend/public/assets/github_button.png
  frontend/src/scenes/Preloader.ts
  frontend/src/scenes/Title.ts
  frontend/src/utils/title.ts
Labels: size/M

#398 アイテムのスケールサイズを変更
  backend/src/game_engine/services/ItemService.ts
  frontend/src/items/Item.ts
Labels: size/S

#401 game header に色をつけて、落ちてくるブロックがヘッダーを透過するのを解消
  frontend/src/scenes/GameHeader.ts
Labels: size/XS

#402 雲がいい感じに出るようにした
  frontend/src/config/config.ts
  frontend/src/scenes/Game.ts
  frontend/src/services/Cloud.ts
Labels: size/M

#408 change README
  README.md
Labels: size/S
